import React, { Component } from "react";
import { BackAndroid, StatusBar, Platform } from "react-native";
import { variables, Drawer } from "native-base";

import getTheme from "../native-base-theme/components";
import material from "../native-base-theme/variables/material";
import platform from "../native-base-theme/variables/platform";

import Home from "./components/home/";
import Header from "./components/Header/";
import Header1 from "./components/Header/1";
import Header2 from "./components/Header/2";
import Header3 from "./components/Header/3";
import Header4 from "./components/Header/4";
import Header5 from "./components/Header/5";
import Header6 from "./components/Header/6";
import Header7 from "./components/Header/7";
import Header8 from "./components/Header/8";
import Anatomy from "./components/anatomy/";
import Footer from "./components/footer/";
import BasicFooter from "./components/footer/basicFooter";
import IconFooter from "./components/footer/iconFooter";
import IconText from "./components/footer/iconText";
import BadgeFooter from "./components/footer/badgeFooter";
import NHBadge from "./components/badge/";
import NHButton from "./components/button/";
import Default from "./components/button/default";
import Outline from "./components/button/outline";
import Rounded from "./components/button/rounded";
import Block from "./components/button/block";
import Full from "./components/button/full";
import Custom from "./components/button/custom";
import Transparent from "./components/button/transparent";
import IconBtn from "./components/button/iconBtn";
import Disabled from "./components/button/disabled";
import NHCard from "./components/card/";
import BasicCard from "./components/card/basic";
import NHCardImage from "./components/card/card-image";
import NHCardShowcase from "./components/card/card-showcase";
import NHCardList from "./components/card/card-list";
import NHCardHeaderAndFooter from "./components/card/card-header-and-footer";
import NHCheckbox from "./components/checkbox/";
import NHDeckSwiper from "./components/deckswiper/";
import NHFab from "./components/fab/";
import BasicFab from "./components/fab/basic";
import MultipleFab from "./components/fab/multiple";
import NHForm from "./components/form/";
import FixedLabel from "./components/form/fixedLabel";
import InlineLabel from "./components/form/inlineLabel";
import FloatingLabel from "./components/form/floatingLabel";
import PlaceholderLabel from "./components/form/placeholder";
import StackedLabel from "./components/form/stacked";
import TextArea from "./components/form/textArea";
import NHIcon from "./components/icon/";
import BasicIcon from "./components/icon/basic";
import IconState from "./components/icon/state";
import SpecificIcon from "./components/icon/specific";
import NHInputGroup from "./components/inputgroup/";
import RegularInput from "./components/inputgroup/regular";
import UnderlineInput from "./components/inputgroup/underline";
import RoundedInput from "./components/inputgroup/rounded";
import IconInput from "./components/inputgroup/iconInput";
import SuccessInput from "./components/inputgroup/success";
import ErrorInput from "./components/inputgroup/error";
import DisabledInput from "./components/inputgroup/disabledInput";
import NHLayout from "./components/layout/";
import RowNB from "./components/layout/row";
import ColumnNB from "./components/layout/column";
import NestedGrid from "./components/layout/nested";
import CustomRow from "./components/layout/customRow";
import CustomCol from "./components/layout/customCol";
import NHList from "./components/list/";
import NHBasicList from "./components/list/basic-list";
import NHListDivider from "./components/list/list-divider";
import NHListSeparator from "./components/list/list-separator";
import NHListHeader from "./components/list/list-headers";
import NHListIcon from "./components/list/list-icon";
import NHListAvatar from "./components/list/list-avatar";
import NHListThumbnail from "./components/list/list-thumbnail";
import NHRadio from "./components/radio/";
import NHSearchbar from "./components/searchbar/";
import NHSpinner from "./components/spinner/";
import NHPicker from "./components/picker/";
import NHTab from "./components/tab/";
import BasicTab from "./components/tab/basicTab";
import ConfigTab from "./components/tab/configTab";
import NHThumbnail from "./components/thumbnail/";
import NHTypography from "./components/typography/";
import SplashPage from "./components/splashscreen/";
import SideBar from "./components/sidebar";
import Segment from "./components/segment";
import BasicSegment from "./components/segment/SegmentHeader";
import AdvSegment from "./components/segment/segmentTab";
import Toast from "./components/toast";
import statusBarColor from "./themes/variables";

class AppNavigator extends Component {
  render() {
    return ;
  }
}

export default AppNavigator;
